### ISSUE TITLE
Was not able to implement your program

### ISSUE THREAD

**Issue by shhivam** [TheBeast007/Air-Mouse#1]
This was what I did:
1. I use Spyder for writing and compiling my python code and same I did with your code. I have not yet run your code but I will tell you at what step I would.
      --> error: pynput not installed
      --> fixed it by installing the same pynput and "import pynput" runs flawlessly
2. Downloaded the Sensor Node Free app from playstore
      --> Opened it,  clicked on the option "stream"
      --> it then asked me 2  options:  1.) Stream live data(XML) and 2.) Stream live data(MQTT)
      --> I clicked on the 1st one, then I checked the boxes for Accelerometer and Light Intensity.
      --> Asked for Target IP Address: I filled my Laptop's IP Add. by looking it up through the command            "ipconfig" in CMD.(Note: My laptop is sharing internet with my mobile through it's[ mobile's ] hotspot service.)
     --> Asked for Port number, I filled 5555 but the thing to note is I modified the value of ip and port in your py program according to what I entered in that android app.
3. Clicked on the activate stream button in the app
4.  Then ran your program in Spyder IDE but nothing happened !
Please help me !

**Comment by the-vishal** [comment]
Hey Shivam,

1.Make sure you are adding the *ip address provided in 2nd last para in
ipconfig* command results.

2.Use airmouse touch with apk provided in repository and for airmouse use
sensor node apk....if second one not works for you , you may give a try to
1st one.


On 11-Feb-2018 3:34 AM, "shhivam" <notifications@github.com> wrote:

This was what I did:

   1. I use Spyder for writing and compiling my python code and same I did
   with your code. I have not yet run your code but I will tell you at what
   step I would.
   --> error: pynput not installed
   --> fixed it by installing the same pynput and "import pynput" runs
   flawlessly
   2. Downloaded the Sensor Node Free app from playstore
   --> Opened it, clicked on the option "stream"
   --> it then asked me 2 options: 1.) Stream live data(XML) and 2.) Stream
   live data(MQTT)
   --> I clicked on the 1st one, then I checked the boxes for Accelerometer
   and Light Intensity.
   --> Asked for Target IP Address: I filled my Laptop's IP Add. by looking
   it up through the command "ipconfig" in CMD.(Note: My laptop is sharing
   internet with my mobile through it's[ mobile's ] hotspot service.)
   --> Asked for Port number, I filled 5555 but the thing to note is I
   modified the value of ip and port in your py program according to what I
   entered in that android app.
   3. Clicked on the activate stream button in the app
   4. Then ran your program in Spyder IDE but nothing happened !
   Please help me !

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/the-vishal/Air-Mouse/issues/1>, or mute the thread

**Comment by shhivam** [comment]
Tried all the things but alas, no effect !
It is weird to ask but did the code run flawlessly on your system ?
I have taken every possible step but could not find the problem.
A suggestion which I think could be the problem: I think script is not able to get the data properly. Kindly check if python is able to grab the data sent by the app correctly by first saving it in a text file using logging functions in python. I am not sure if i am right but you can atleast try if the system is also not working well.
Anyways, thank you for replying ! and yes, I am really very excited about this piece of tech.

**Comment by the-vishal** [comment]
yes, even few weeks ago another github user came up with same problem but that fixes with above two points

**Comment by the-vishal** [comment]
you can give a try to this  https://simplypython.quora.com/CHAPTER-2-Remote-Locking-using-Android?share=a9d7cc71&srid=uZSjb

If that is that working for you!

**Comment by the-vishal** [comment]
I just checked that, it works : https://youtu.be/DK0oLFoKDV8

**Comment by shhivam** [comment]
I will surely try this in coming 2 days. 
thanks, man !
